compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  libc:
    - glibc
    - musl
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.11.0.cjs
